### ISSUE TITLE
turning off transformchain with request

### ISSUE THREAD

**Issue by flipmcf** [plone/plone.transformchain#11]
The documentation says: 

> if you need to turn off transformations for a particular request, you can set a key in request.environ:
> 
> request.environ['plone.transformchain.disable'] = True

So, I am inferring that this should work to turn off the transformchain:

```
$curl -v -L --header "plone.transformchain.disable: 1" localhost:8080/Plone

*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /Plone HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> plone.transformchain.disable: 1
> 
```

But it seems not to work:

```
> /home/mcfaddenm/.../eggs/plone.transformchain-2.0.2-py3.8.egg/plone/transformchain/transformer.py(43)__call__()
-> if request.environ.get(DISABLE_TRANSFORM_REQUEST_KEY, False):
(Pdb) request.environ
{'REMOTE_ADDR': '127.0.0.1', 'REMOTE_HOST': '127.0.0.1', 'REMOTE_PORT': '50106', 'REQUEST_METHOD': 'GET', 'SERVER_PORT': '8080', 'SERVER_NAME': '...', 'SERVER_SOFTWARE': 'waitress', 'SERVER_PROTOCOL': 'HTTP/1.1', 'SCRIPT_NAME': '', 'PATH_INFO': '/Plone', 'QUERY_STRING': '', 'wsgi.url_scheme': 'http', 'wsgi.version': (1, 0), 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.multithread': True, 'wsgi.multiprocess': False, 'wsgi.run_once': False, 'wsgi.input': <_io.BytesIO object at 0x7fc44fdcea90>, 'wsgi.file_wrapper': <class 'waitress.buffers.ReadOnlyFileBasedBuffer'>, 'wsgi.input_terminated': True, 'HTTP_HOST': 'localhost:8080', 'HTTP_USER_AGENT': 'curl/7.68.0', 'HTTP_ACCEPT': '*/*', 'HTTP_PLONE.TRANSFORMCHAIN.DISABLE': '1', 'Zope2.httpexceptions': <ZPublisher.httpexceptions.HTTPExceptionHandler object at 0x7fc454ed4880>}
(Pdb) DISABLE_TRANSFORM_REQUEST_KEY
'plone.transformchain.disable'

```

It seems that the header was translated from 'plone.transformchain.disable' to 'HTTP_PLONE.TRANSFORMCHAIN.DISABLE'

Is this expected behavior or a bug?  

Plone 5.2.4 (5212)
CMF 2.5.0
Zope 4.5.5
Python 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
PIL 6.2.2 (Pillow)
WSGI: On
Server: waitress 1.4.4

**Comment by davisagli** [comment]
Setting a request header is not the same as setting a key in request.environ (which includes a normalized form of request headers as well as other info from other sources). You should be able to set `request.environ['plone.transformchain.disable'] = True` from Python as mentioned, but I don't think there is a way to do this from outside the server.

If it happens to be the Diazo transform that you want to disable, plone.app.theming does have a way to do that via a request header: https://pypi.org/project/plone.app.theming/#advanced-disable-diazo-transformation-by-setting-the-x-theme-disabled-header

**Comment by flipmcf** [comment]
Thanks.  I thought this might have been the answer.  Seemed a bit too powerful of a move for an anonymous request.
